osx_image: xcode10.1
language: swift

cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - set -o pipefail
  - fastlane tests

deploy:
  skip_cleanup: true
  provider: script
  script: fastlane screenshots && fastlane nightly
