osx_image: xcode10
language: swift

cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - fastlane tests

deploy:
  - fastlane screenshots
  - fastlane nightly
